import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Markdown from 'react-markdown';
import { FileText, SearchCode, Lightbulb, Map, X, Check } from 'lucide-react';

/* ── Agent definitions for timeline ──────────────────────────────────── */
const AGENTS = [
  { icon: FileText, name: 'Extractor Agent', label: 'Extract Methodologies', color: 'var(--color-violet)' },
  { icon: SearchCode, name: 'Gap Analyzer', label: 'Analyze Research Gaps', color: 'var(--color-blue)' },
  { icon: Lightbulb, name: 'Hypothesis Engine', label: 'Generate Hypotheses', color: 'var(--color-rose)' },
  { icon: Map, name: 'Roadmap Planner', label: 'Draft 6-Month Plan', color: 'var(--color-electric)' },
];

/* ── Mock streamed output ────────────────────────────────────────────── */
const MOCK_SECTIONS = [
  {
    content: `## Extracted Methodologies

### Paper 1: Mitigating Multimodal Hallucination via Phase-wise Self-reward
- **PSRD (Phase-wise Self-Reward Decoding):** An online hallucination correction method guided by phase-wise self-reward signals during the decoding process
- **Lightweight Reward Model:** A model distilled from LVLMs to provide on-the-fly guidance for targeted intervention at each semantic phase
- **Phase-wise Dynamic Patterns:** Empirical observation that visual hallucination exhibits dynamic patterns, peaking at the onset of each semantic phase

### Paper 2: THaMES — End-to-End Hallucination Mitigation Tool
- **In-Context Learning (ICL):** Provides examples within the prompt to guide model behavior and reduce hallucinated outputs
- **Retrieval Augmented Generation (RAG):** Retrieves relevant information from an external knowledge base to ground generation in factual data
- **Parameter-Efficient Fine-tuning (PEFT):** Adapts a subset of model parameters for domain-specific hallucination reduction

### Paper 3: Hallucination Detection with Small Language Models
- **Multi-SLM Verification Framework:** Combines outputs from several small models to cross-verify responses generated by larger LLMs
- **Vectorized Knowledge Retrieval:** Stores and retrieves contextual information in embedding format for high-precision RAG pipelines
- **Token Probability Analysis:** Detects hallucinations by analyzing the likelihood of SLMs generating confirmatory tokens`,
  },
  {
    content: `## Research Gap Analysis

### Gap 1: No Unified Hallucination Taxonomy
None of the reviewed papers provide a comprehensive, universally accepted taxonomy of hallucination types. Without granular classification (factual confabulation, logical inconsistency, semantic drift, omission), mitigation strategies remain too broad and evaluation frameworks cannot capture the full spectrum of the problem.

### Gap 2: Mitigation vs. Creativity Trade-off
Several papers propose mitigation methods but **none explicitly quantify** the trade-offs introduced. Does stringent hallucination mitigation limit the model's creativity, fluency, diversity, or ability to generate speculative content? This fundamental tension is unaddressed.

### Gap 3: Reactive Over Proactive Strategies
Most proposed methods are *reactive* — correcting during decoding or detecting post-generation. Concrete proactive architectural designs explicitly designed to prevent hallucinations from forming during pre-training remain largely underspecified.

### Gap 4: Explainability Deficit
While "attention-based circuits" provide insight into how models learn facts, the direct link to *why specific hallucinations occur* at a mechanistic level remains an open problem critical for building trust and improving models systematically.`,
  },
  {
    content: `## Novel Research Hypotheses

### Hypothesis 1: Factual-Confabulation Discriminator Loss
Training LLMs with a novel loss function that explicitly penalizes intermediate activation patterns empirically correlated with known hallucination types will produce models inherently more resistant to factual confabulation during inference — without post-hoc correction.

> **Expected Outcome:** 15-25% reduction in factual inaccuracies across TruthfulQA and FactScore benchmarks under challenging, adversarial prompts.

### Hypothesis 2: Hallucination-Creativity Frontier Optimization
A multi-objective Pareto optimization framework that simultaneously minimizes taxonomically-defined hallucination types and maximizes desirable generation attributes (creativity, fluency, conciseness) will enable deployment of task-specific model variants operating along a quantifiable frontier.

> **Expected Outcome:** A spectrum of LLM variants enabling informed model selection — high-accuracy variants for scientific summaries, high-creativity variants for brainstorming.

### Hypothesis 3: Adaptive Contextual Prevention System
Combining real-time dynamic knowledge graphs with an ensemble of context-aware predictive modules will achieve superior mitigation by inferring hallucination risk *before* token decoding, enabling preemptive intervention rather than post-generation correction.

> **Expected Outcome:** 30% improvement in hallucination resistance in rapidly-evolving knowledge domains compared to static RAG baselines.`,
  },
  {
    content: `## 6-Month Research Roadmap

### Month 1 — Foundation & Taxonomy
- **Deliverable:** Mechanistic interpretability tooling setup (TransformerLens, Captum)
- **Deliverable:** Unified Hallucination & Creativity Taxonomy v1.0 with annotation protocol
- **Resources:** 2× A100 GPUs, 3 ML researchers, annotation platform
- **Success Metric:** Clear taxonomy definitions, working activation analysis pipeline

### Month 2 — Core Development & Prototyping
- **Deliverable:** Prototype Factual-Confabulation Discriminator Loss function
- **Deliverable:** Annotated dataset of 2,000+ activation-hallucination pairs
- **Deliverable:** Dynamic knowledge graph retrieval system prototype
- **Risk Factor:** Discriminator correlation may prove weak at this stage

### Month 3 — Integration & Initial Experiments
- **Deliverable:** LLM fine-tuning with Discriminator Loss on Llama-3-8B
- **Deliverable:** Pareto optimization framework prototype with 3-4 reward models
- **Deliverable:** FIPT (Factual Integrity Preserving Fine-tuning) first run
- **Success Metric:** Measurable hallucination reduction in at least one trained model

### Month 4 — Refinement & Deep Experimentation
- **Deliverable:** Expanded evaluation across wider factual integrity datasets
- **Deliverable:** Multiple LLM variants positioned on the Hallucination-Creativity Frontier
- **Deliverable:** ACHP orchestration system with 3 adaptive mitigation strategies

### Month 5 — Comprehensive Evaluation
- **Deliverable:** Final model variants with cross-benchmark evaluation (TruthfulQA, FactScore, HaluEval)
- **Deliverable:** ACHP v1.0 end-to-end system integration and latency testing
- **Deliverable:** Cross-hypothesis insights report synthesizing all findings

### Month 6 — Documentation & Dissemination
- **Deliverable:** 4 research paper drafts (one per hypothesis)
- **Deliverable:** Open-source codebase release with model checkpoints on HuggingFace
- **Deliverable:** Conference submission preparation targeting NeurIPS / ACL / EMNLP
- **Success Metric:** Peer-reviewed validation of at least 2 hypotheses`,
  },
];

export default function OutputPanel({ isVisible, query, onClose, onAgentProgress }) {
  const [displayedContent, setDisplayedContent] = useState('');
  const [currentSection, setCurrentSection] = useState(0);
  const [isStreaming, setIsStreaming] = useState(false);
  const scrollRef = useRef(null);

  useEffect(() => {
    if (!isVisible) {
      setDisplayedContent('');
      setCurrentSection(0);
      setIsStreaming(false);
      return;
    }

    setIsStreaming(true);
    setDisplayedContent('');
    setCurrentSection(0);

    const header = `# VertexFlow Research Report\n**Query:** ${query}\n\n---\n\n`;
    const allContent = MOCK_SECTIONS.map((s) => `${s.content}\n\n---\n\n`).join('');
    const totalText = header + allContent;

    let charIndex = 0;

    const interval = setInterval(() => {
      charIndex += 4;
      if (charIndex >= totalText.length) {
        setDisplayedContent(totalText);
        setIsStreaming(false);
        setCurrentSection(MOCK_SECTIONS.length - 1);
        clearInterval(interval);
        return;
      }
      setDisplayedContent(totalText.slice(0, charIndex));

      if (scrollRef.current) {
        scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
      }

      let accumulated = header.length;
      for (let i = 0; i < MOCK_SECTIONS.length; i++) {
        const sectionLen = MOCK_SECTIONS[i].content.length + 8;
        accumulated += sectionLen;
        if (charIndex < accumulated) {
          if (i !== currentSection) {
            setCurrentSection(i);
            if (onAgentProgress) onAgentProgress(i);
          }
          break;
        }
      }
    }, 6);

    return () => clearInterval(interval);
  }, [isVisible, query]);

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.3 }}
          style={{ position: 'fixed', inset: 0, zIndex: 40, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '24px' }}
        >
          {/* Backdrop */}
          <div style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(8px)' }} onClick={onClose} />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.98, y: 10 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.98, y: 10 }}
            transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            className="glass"
            style={{
              position: 'relative',
              width: '94%',
              maxWidth: '1200px',
              height: '85vh',
              borderRadius: '2px',
              display: 'flex',
              flexDirection: 'column',
              overflow: 'hidden',
              background: 'rgba(7,4,15,.88)', // Slightly darker than standard glass for readability
              border: '1px solid rgba(123,45,191,.25)',
              boxShadow: '0 0 60px rgba(123,45,191,.15)'
            }}
          >
            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 24px', borderBottom: '1px solid rgba(123,45,191,.2)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
                <div style={{ width: '7px', height: '7px', borderRadius: '50%', background: 'var(--color-electric)', boxShadow: '0 0 12px var(--color-electric)', flexShrink: 0 }}></div>
                <div>
                  <h2 className="hud" style={{ color: 'var(--color-electric)', marginBottom: '2px' }}>Research Synthesis Report</h2>
                  <p className="body-sm" style={{ color: 'rgba(184,200,216,.5)' }}>{query}</p>
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                {isStreaming ? (
                  <span className="hud" style={{ color: 'var(--color-gold-lt)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: 'var(--color-gold-lt)' }} className="animate-pulse" />
                    Synthesizing
                  </span>
                ) : (
                  <span className="hud" style={{ color: 'rgba(52,211,153,1)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <Check size={12} /> Complete
                  </span>
                )}
                <button
                  onClick={onClose}
                  style={{
                    width: '32px', height: '32px', borderRadius: '2px', background: 'rgba(123,45,191,.08)',
                    border: '1px solid rgba(123,45,191,.2)', display: 'flex', alignItems: 'center', justifyContent: 'center',
                    cursor: 'pointer', transition: 'all .3s', color: 'rgba(184,200,216,.7)'
                  }}
                  className="hover:bg-[rgba(155,77,255,.15)] hover:text-white"
                >
                  <X size={14} />
                </button>
              </div>
            </div>

            {/* Two-column Layout */}
            <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
              {/* Left Sidebar — Timeline */}
              <div style={{ width: '260px', flexShrink: 0, borderRight: '1px solid rgba(123,45,191,.2)', padding: '32px 24px', overflowY: 'auto' }}>
                <h3 className="label" style={{ color: 'rgba(184,200,216,.4)', marginBottom: '32px' }}>
                  Pipeline Status
                </h3>
                
                <div className="tl-wrap" style={{ padding: '0 0 0 12px' }}>
                  <div className="tl-line" style={{ left: '17px', top: '24px', bottom: '24px', width: '1px', height: 'auto', background: 'rgba(123,45,191,.15)' }}></div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '32px', position: 'relative', zIndex: 2 }}>
                    {AGENTS.map((agent, i) => {
                      const Icon = agent.icon;
                      const isActive = i === currentSection && isStreaming;
                      const isComplete = i < currentSection || (!isStreaming && i <= currentSection && displayedContent);

                      let dotBg = 'var(--color-deep)';
                      let dotBorder = 'rgba(123,45,191,.3)';
                      let textColor = 'rgba(184,200,216,.4)';

                      if (isComplete) {
                        dotBg = agent.color;
                        dotBorder = agent.color;
                        textColor = 'var(--color-white)';
                      } else if (isActive) {
                        dotBg = 'transparent';
                        dotBorder = agent.color;
                        textColor = agent.color;
                      }

                      return (
                        <div key={i} style={{ display: 'flex', gap: '16px', alignItems: 'flex-start' }}>
                          <div style={{
                            width: '12px', height: '12px', borderRadius: '50%',
                            background: dotBg, border: `2px solid ${dotBorder}`,
                            marginTop: '4px', flexShrink: 0,
                            boxShadow: isActive ? `0 0 12px ${agent.color}` : 'none',
                            transition: 'all .4s'
                          }} />
                          <div>
                            <p style={{ fontSize: '13px', fontWeight: 500, color: textColor, transition: 'color .4s' }}>{agent.name}</p>
                            <p className="hud" style={{ color: isActive ? 'rgba(184,200,216,.6)' : 'rgba(184,200,216,.3)', marginTop: '4px' }}>{agent.label}</p>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>

              {/* Right Main Content */}
              <div ref={scrollRef} style={{ flex: 1, overflowY: 'auto', padding: '40px 48px', scrollBehavior: 'smooth' }}>
                <div className="markdown-body">
                  <Markdown>{displayedContent}</Markdown>
                  {isStreaming && (
                    <span style={{ display: 'inline-block', width: '8px', height: '18px', background: 'var(--color-electric)', marginLeft: '4px', animation: 'typing-cursor .7s step-end infinite' }} />
                  )}
                </div>
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
